import React from 'react';
import {timeLabel} from './api';
const labels={A:'A',B:'B',C:'C',D:'D',none:'Keiner',hybrid:'A + B'};
const instruments={drums:'Drums',bass:'Bass',other:'Übrige Begleitung',piano:'Klavier',electric_guitar:'E-Gitarre',acoustic_guitar:'Akustische Gitarre',synthesizer:'Synthesizer',strings:'Streicher',wind:'Bläser'};
const melodicStems=new Set(['piano','electric_guitar','acoustic_guitar','synthesizer','strings','wind']);
const baseRouting=s=>s.instrumental==='hybrid'?{drums:'B',bass:'A',other:'A'}:s.backing_stem&&s.backing_stem!=='instrumental'?{[s.backing_stem]:s.instrumental}:{drums:s.instrumental,bass:s.instrumental,other:s.instrumental};
export function Arrangement({sections,setSections,onPlan,onIntro,onInstrumentPlan,busy,bpm,setBpm,keyMatch,setKeyMatch,resolvedBpm,sources=['A','B'],fullSources=[],fullStems=false,onSimple}){
 const change=(i,key,value)=>setSections(sections.map((s,n)=>n===i?{...s,[key]:value}:s));
 const changeInstrument=(i,stem,value)=>setSections(sections.map((s,n)=>n===i?{...s,instrument_sources:{...(Object.keys(s.instrument_sources||{}).length?s.instrument_sources:baseRouting(s)),[stem]:value},instrument_levels_db:{...s.instrument_levels_db}}:s));
 const changeInstrumentLevel=(i,stem,value)=>setSections(sections.map((s,n)=>n===i?{...s,instrument_levels_db:{...s.instrument_levels_db,[stem]:value}}:s));
 const changeBase=(i,value)=>setSections(sections.map((s,n)=>{if(n!==i)return s;const routing=Object.keys(s.instrument_sources||{}).length?{...s.instrument_sources,...baseRouting({...s,instrumental:value})}:{};return {...s,instrumental:value,instrument_sources:routing};}));
 let bar=1;
 return <section className="arrangement panel">
  <div className="section-heading"><h2>Dein Arrangement</h2><div className="plan-controls"><button disabled={busy} onClick={onPlan}>✧ &nbsp; Zusammenhängend planen</button><label>Zieltempo <input aria-label="Zieltempo" type="number" min="60" max="200" disabled={busy} placeholder={String(resolvedBpm||'Auto')} value={bpm} onChange={e=>setBpm(e.target.value)}/></label><button className="subtle" disabled={busy||bpm===''} onClick={()=>setBpm('')}>Auto-Tempo</button><label className="toggle-label">Tonart anpassen <input className="toggle" type="checkbox" checked={keyMatch} onChange={e=>setKeyMatch(e.target.checked)}/></label></div></div>
  {!sections.length?<div className="empty-plan">Wähle mindestens zwei Songs und lass dir einen Abschnittsplan vorschlagen.</div>:<>
   <p className="result-note" aria-live="polite">Geplante Länge: <strong>{resolvedBpm>0?timeLabel(sections.reduce((sum,s)=>sum+s.bars,0)*240/resolvedBpm):'–'}</strong> · Beim musikalischen Planen sind etwa drei Minuten möglich, wenn die Passagen zusammenpassen.</p>
   <div className="timeline" aria-label="Arrangement in Takten">{sections.map((s,i)=>{const start=bar;bar+=s.bars;return <div key={i} className={'timeline-section color-'+(s.effect==='drop'?'drop':s.vocal)} style={{flex:s.bars}}><strong>{s.name}</strong><span>{s.bars} Takte</span><small>{start}</small></div>})}<small className="end-bar">{bar}</small></div>
   <div className="table-scroll"><table><thead><tr><th>Abschnitt</th><th>Takte</th><th>Gesang</th><th>Instrumental</th>{sources.map(x=><th key={x}>Start {x} · Sek.</th>)}<th><span className="sr-only">Entfernen</span></th></tr></thead><tbody>{sections.map((s,i)=><tr key={i}>
    <td><span className={'dot dot-'+(s.effect==='drop'?'drop':s.vocal)}/><input aria-label={`Name Abschnitt ${i+1}`} className="name-input" value={s.name} maxLength="60" onChange={e=>change(i,'name',e.target.value)}/></td>
    <td><input aria-label={`Takte Abschnitt ${i+1}`} type="number" min="1" max="32" value={s.bars} onChange={e=>change(i,'bars',Number(e.target.value))}/></td>
    <td><select aria-label={`Gesang Abschnitt ${i+1}`} value={s.vocal} onChange={e=>change(i,'vocal',e.target.value)}>{['none',...sources].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></td>
    <td><select aria-label={`Instrumental Abschnitt ${i+1}`} value={s.instrumental} onChange={e=>changeBase(i,e.target.value)}>{[...sources,'hybrid'].map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></td>
    {sources.map(s=>s.toLowerCase()).map(x=><td key={x}><input aria-label={`Start ${x.toUpperCase()} Abschnitt ${i+1}`} type="number" min="0" step="0.1" value={s['start_'+x]??0} onChange={e=>change(i,'start_'+x,Number(e.target.value))}/></td>)}
    <td><button className="remove" aria-label={`Abschnitt ${i+1} entfernen`} disabled={sections.length===1} onClick={()=>setSections(sections.filter((_,n)=>n!==i))}>×</button></td>
   </tr>)}</tbody></table></div>
   <div className="arrangement-foot"><p>Baue ein Intro aus dem Motiv der folgenden Begleitung. Bass und Drums kommen schrittweise dazu.</p><button className="subtle" disabled={busy} onClick={onSimple}>Einfacher Plan</button><button className="subtle" disabled={busy} onClick={onIntro}>Intro neu aufbauen</button><button className="subtle" disabled={sections.length>=16} onClick={()=>setSections([...sections,{...sections.at(-1),name:'Neuer Teil',effect:'normal',bars:8}])}>+ Abschnitt</button></div>
   {fullStems&&<details className="fine instrument-plan"><summary>Einzelinstrumente pro Abschnitt planen</summary><p>Jede Spur kann aus A–D stammen oder pausieren. Melodische Einzelspuren sind nur bei Songs mit vollständiger LALAL-Trennung verfügbar. Die automatische Verteilung behält eine zusammenhängende Begleitung und ergänzt höchstens einen leisen Akzent aus einem anderen Song. „Übrige Begleitung“ enthält auch melodische Anteile; dieselben Instrumente daraus zusätzlich einzuschalten kann sie doppeln.</p><button className="subtle" disabled={busy} onClick={onInstrumentPlan}>✧ Instrumente automatisch verteilen</button>{sections.map((s,i)=>{const routing=Object.keys(s.instrument_sources||{}).length?s.instrument_sources:baseRouting(s);return <div className="instrument-section" key={i}><div className="instrument-section-heading"><strong>{i+1}. {s.name}</strong><button className="subtle" disabled={busy} onClick={()=>setSections(sections.map((item,n)=>n===i?{...item,instrument_sources:{},instrument_levels_db:{},backing_stem:'instrumental'}:item))}>Ganzes Instrumental</button></div><div className="instrument-grid">{Object.entries(instruments).map(([stem,label])=><div className="instrument-control" key={stem}><label>{label}<select aria-label={`${label} Abschnitt ${i+1}`} disabled={busy} value={routing[stem]||'off'} onChange={e=>changeInstrument(i,stem,e.target.value)}><option value="off">Aus</option>{sources.map(source=><option key={source} value={source} disabled={melodicStems.has(stem)&&!fullSources.includes(source)}>Track {source}{melodicStems.has(stem)&&!fullSources.includes(source)?' · keine LALAL-Instrumente':''}</option>)}</select></label>{routing[stem]&&routing[stem]!=='off'&&<label>Pegel · dB<input aria-label={`${label} Pegel Abschnitt ${i+1}`} type="number" min="-24" max="6" step="1" disabled={busy} value={s.instrument_levels_db?.[stem]??0} onChange={e=>changeInstrumentLevel(i,stem,Number(e.target.value))}/></label>}</div>)}</div></div>})}</details>}
   <details className="fine"><summary>Feinabstimmung pro Abschnitt</summary><p>A + B kombiniert Drums aus B mit Bass und übrigen Instrumenten aus A. Nach der musikalischen Analyse rasten Einstiege auf erkannte Taktanfänge ein; manuelle BPM überschreiben dieses Raster.</p>{sections.map((s,i)=><div className="fine-row" key={i}><strong>{s.name}</strong><label>Gesang · dB<input aria-label={`Gesangspegel Abschnitt ${i+1}`} type="number" min="-18" max="12" value={s.vocal_db} onChange={e=>change(i,'vocal_db',Number(e.target.value))}/></label><label>Musik · dB<input type="number" min="-18" max="12" value={s.instrumental_db} onChange={e=>change(i,'instrumental_db',Number(e.target.value))}/></label><label>Gesang · Versatz in Beats<input type="number" min="-8" max="8" step="0.25" value={s.vocal_offset} onChange={e=>change(i,'vocal_offset',Number(e.target.value))}/></label><label>Verlauf<select value={s.effect} onChange={e=>change(i,'effect',e.target.value)}>{['normal','intro','build','drop','outro'].map(x=><option key={x}>{x}</option>)}</select></label></div>)}</details>
  </>}
 </section>
}
