import React,{useRef} from 'react';
import {timeLabel} from './api';
export function ResultPanel({job,result,history,onSelect,onRender,onCancel,busy,ready}){
 const player=useRef(null),resume=useRef(null);
 const selectResult=next=>{resume.current=player.current?{time:player.current.currentTime,playing:!player.current.paused}:null;onSelect(next)};
 const restore=()=>{const saved=resume.current;resume.current=null;if(saved&&player.current){player.current.currentTime=Math.min(saved.time,Math.max(0,player.current.duration-.05));if(saved.playing)player.current.play().catch(()=>{});}};
 const base=result?`/api/exports/${result.id}`:'';
 return <section className="panel result"><div className="section-heading"><h2>Dein Mashup</h2><div className="render-actions"><button disabled={busy||!ready} onClick={()=>onRender(true)}>▶ &nbsp; 32 Takte vorhören</button><button className="primary" disabled={busy||!ready} onClick={()=>onRender(false)}>▥ &nbsp; Arrangement rendern</button></div></div>
  {job&&<div className={'job job-'+job.status} role="status" aria-live="polite"><div><span>{job.message}</span>{busy&&<button className="subtle" onClick={onCancel}>Abbrechen</button>}</div>{busy&&<progress value={job.progress} max="100"/>}</div>}
  {result?<><div className="result-caption"><span>{result.name} · {timeLabel(result.duration)} · {result.bpm} BPM · B {result.pitch_b>=0?'+':''}{result.pitch_b} Halbtöne</span>{history.length>1&&<select aria-label="Vorherige Ergebnisse" value={result.id} onChange={e=>selectResult(history.find(x=>x.id===e.target.value))}>{history.map((x,i)=><option key={x.id} value={x.id}>{x.name} · {x.bpm} BPM · {timeLabel(x.duration)} · Version {history.length-i}</option>)}</select>}</div><p className="result-note">{result.track_a} × {result.track_b}</p><audio ref={player} onLoadedMetadata={restore} className="result-audio" controls src={base+'/mashup.mp3'} preload="metadata"/><div className="downloads"><a href={base+'/mashup.wav'} download>↓ WAV · 24 Bit</a><a href={base+'/mashup.mp3'} download>↓ MP3 · 320 kbps</a><a href={base+'/stems.zip'} download>↓ Stems für die DAW</a><a href={base+'/arrangement.json'} download>↓ Arrangement</a></div><p className="result-note">{result.separation&&`Trennung: A ${result.separation.A==='hq'?'RoFormer':'Demucs'} · B ${result.separation.B==='hq'?'RoFormer':'Demucs'}. `}{result.warnings?.join(' ')}</p></>:<div className="result-empty">{busy?'Dein Mix entsteht. Die erste Stimmtrennung benötigt einige Minuten.':'Bereit für deinen ersten Mix. Die Vorschau spielt die ersten beiden Gesangsteile.'}</div>}
 </section>
}
